### ISSUE TITLE
Update mot files affected by change to handling of MotionType

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-models#87] opened 2018-08-10 21:41 UTC
- [x] Strength of Simulation Example (definite)
- [x] Apoorva's motion files on her simtk page (@james)
- [x] Check on the wrist model (checked)
- [x] Neck model https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=253&t=9516&p=0&start=0&view=

Review other models

**Comment by aseth1** [comment] 2018-08-17 22:36
First step check on the models to verify they need updating.

**Comment by chrisdembia** [comment] 2018-08-24 21:26
@aymanhab Ideally we could use `org.opensim.modeling.opensimSimulation.updatePre40KinematicsFilesFor40MotionType()` in the GUI scripting shell but this does not work:

```
>>> org.opensim.modeling.opensimSimulation.updatePre40KinematicsFilesFor40MotionType()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
AttributeError: type object 'org.opensim.modeling.opensimSimulation' has no attribute 'updatePre40KinematicsFilesFor40MotionType'
>>> 
```

I'm surprised, because `org.opensim.modeling.opensimCommon.LoadOpenSimLibrary()` works.

Any ideas? Do we have to place explicit imports somewhere?

**Comment by aymanhab** [comment] 2018-08-24 21:35
opensimSimulation.java is empty so no surprise here. Need to follow workflow/signatures similar to LoadOpenSimLibrary.

**Comment by aymanhab** [comment] 2018-08-24 21:40
Where is the method defined so I can track the wrapping issue?

**Comment by chrisdembia** [comment] 2018-08-24 21:46
Uh oh... the contents of the following two JAR files are different:

1. `/Applications/OpenSim 4.0-2018-08-23-04e6293/OpenSim 4.0-2018-08-23-04e6293.app/Contents/Resources/OpenSim/OpenSim/modules/org-opensim-modeling.jar`

```
14:40 /A/O/O/C/R/O/O/modules javap -cp org-opensim-modeling.jar org.opensim.modeling.opensimSimulation
Compiled from "opensimSimulation.java"
public class org.opensim.modeling.opensimSimulation {
  public org.opensim.modeling.opensimSimulation();
}
```

2. `/Applications/OpenSim 4.0-2018-08-23-04e6293/OpenSim 4.0-2018-08-23-04e6293.app/Contents/Resources/OpenSim/sdk/Java/org-opensim-modeling.jar`

```
14:42 /A/O/O/C/R/O/O/modules javap -cp org-opensim-modeling.jar org.opensim.modeling.opensimSimulation
Compiled from "opensimSimulation.java"
public class org.opensim.modeling.opensimSimulation {
  public org.opensim.modeling.opensimSimulation();
  public static org.opensim.modeling.State simulate(org.opensim.modeling.Model, org.opensim.modeling.State, double, boolean);
  public static org.opensim.modeling.State simulate(org.opensim.modeling.Model, org.opensim.modeling.State, double);
  public static void updatePre40KinematicsFilesFor40MotionType(org.opensim.modeling.Model, org.opensim.modeling.StdVectorString, java.lang.String);
  public static void updatePre40KinematicsFilesFor40MotionType(org.opensim.modeling.Model, org.opensim.modeling.StdVectorString);
}
```

The function is defined in OpenSim/Simulation/SimulationUtilities.h and is properly wrapped (as indicated above).

The issue seems to be that the Java bindings source code was not updated. This is confusing because the CI scripts run `CopyOpenSimCore` before building the GUI. How are the java files out of sync?

**Comment by chrisdembia** [comment] 2018-08-24 21:52
Maybe the issue is that we are not setting `overwrite=true`?

https://github.com/opensim-org/opensim-gui/blob/bc07378db8ab1cc5caec67776b54ff244e25a5d6/Gui/opensim/build.xml#L47

**Comment by aymanhab** [comment] 2018-08-24 22:00
I think you're right. In the past it didn't matter because I usually update the wrapping manually by making a PR to checkin SWIG output

**Comment by chrisdembia** [comment] 2018-08-27 19:35
Now that https://github.com/opensim-org/opensim-gui/pull/970 is merged, this issue should be easier to work on.

**Comment by scrum2a** [comment] 2018-08-28 17:05
To discuss: it seems we might have to update the models to 4.0 as well? Bah.

**Comment by scrum2a** [comment] 2018-08-29 17:07
We should leave the models as 3.3 but correct the `motion_type` property (to `Coupled`) in those 3.3 model files.

**Comment by aymanhab** [comment] 2018-08-31 16:25
Strength of simulation model, .mot files updated, not sure the need to keep around/update Stance/Reference/{CMC,RRA}/{*_kinematics_q, *_kinematics_u, *_kinematics_dudt} all specify inDegrees=yes in their headers. @chrisdembia

**Comment by chrisdembia** [comment] 2018-08-31 16:50
Perhaps we should update the references by re-running the tools? I know we wanted the references to not be altered but I'm not sure what else we could do.

**Comment by aymanhab** [comment] 2018-08-31 20:26
I'm trying to rerun the tools but the model takes off, the tutorial suggests iterating many times so I'm not sure what is in Reference to begin with. I'm leaning to just update the input .mot files and have somebody familiar with the exercise/Reference run it.

**Comment by chrisdembia** [comment] 2018-08-31 20:28
When you run the tool, does the output `Kinematics_q` file have the correct "units" (is the patella coordinate left alone)?

**Comment by aymanhab** [comment] 2018-08-31 20:53
First raw is
time	pelvis_tilt	pelvis_tx	pelvis_ty	hip_flexion_r	knee_angle_r	knee_angle_pat_r	ankle_angle_r
      0.80000000	    1.55034805	      0.03759029	      1.05857320	     20.49867298	    -26.08881433	     -0.45533571	      8.59217031

So knee_angle_pat_r appears to be not converted to degrees. The Reference folder however contains an adjusted model that also needs fixing or recreation to have correct motionType

**Comment by aymanhab** [comment] 2018-09-04 18:07
Since Reference folder can't be recreated in 3.3 format and the reference model is a result of some unknown iterations over RRA (adjusted) I'm suggesting we remove the Reference folder altogether. Thoughts @chrisdembia @aseth1 @jenhicks

**Comment by aymanhab** [comment] 2018-09-04 20:03
Will update reference model by hand to have correct coordinate motion-type then run RRA, CMC in 3.3 and update reference

**Comment by jenhicks** [comment] 2018-09-04 20:33
@aseth1 For Apoorva's model, can you add notes about exactly what needs to get updated.

**Comment by jenhicks** [comment] 2018-09-04 20:35
We will leave the Neck Model out of the 9.4.2018 sprint.

**Comment by aseth1** [comment] 2018-09-04 22:35
For Apoorva's model, we need to update:

1. The `MotionType` for the *knee_angle_r_beta* must be set to `Coupled` (and same for *l_beta*).
2. All motion files in the *Reference* folder that are **inDegrees* must have the conversion of *knee_angle_#_beta* columns into degrees, undone.

**Comment by aymanhab** [comment] 2018-09-05 16:38
Running the tutorial in 3.3 results in slightly different results and it becomes impossible to validate the Reference. Model files in Reference folders are even earlier version than 3.3. I ended up doing the following:
- updated the model files manually to use coupled instead of rotational for knee_angle_pat_r	
- Ran the utility to convert .sto/.mot files under Reference that were in degrees.
- Recreated the simulation in 4.0 using the input files and results looked reasonable (RRA model doesn't take off, avg_residuals are small/close to reference).
That's likely the most we can do without recreating the whole Reference folder models/files in 4.0 format

**Comment by carmichaelong** [comment] 2018-09-06 20:55
#94 was created to fix the files in the repo.

Inspecting the simtk page, the following files are likely to be affected:
1. From `FullBodyModel.zip`:
- `Rajagopal2015.osim`
2. From `ModelWithSampleSimulations`:
- `Rajagopal2015.osim`
- `CMC/run/subject_run_adjusted.osim`
- `CMC/run/results/cmc_Kinematics_q.sto`
- `CMC/walk/subject_walk_adjusted.osim`
- `CMC/walk/results/cmc_Kinematics_q.sto`
- `IK/results_run/ik_output_run.mot`
- `IK/results_walk/ik_output_walk.mot`
- `RRA/run/subject_run_rra1.osim`
- `RRA/run/subject_run_rra2.osim`
- `RRA/run/subject_run_rra3.osim`
- `RRA/run/results_rra_1/rra_run_1_Kinematics_q.sto`
- `RRA/run/results_rra_2/rra_run_2_Kinematics_q.sto`
- `RRA/run/results_rra_3/rra_run_3_Kinematics_q.sto`
- `RRA/walk/subject_walk_rra1.osim`
- `RRA/walk/subject_walk_rra2.osim`
- `RRA/walk/results_rra_1/rra_walk_1_Kinematics_q.sto`
- `RRA/walk/results_rra_2/rra_walk_2_Kinematics_q.sto`
- `Scale/subject_scaled_run.osim`
- `Scale/subject_scaled_walk.osim`

**Comment by chrisdembia** [comment] 2018-09-07 18:09
In daily scrum, we discussed whether or not we should update all the Rajagopal files on SimTK.

**Comment by chrisdembia** [comment] 2018-09-07 18:26
For the neck model, perhaps we can just post a thread to https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=253&pluginname=phpBB

**Comment by scrum2a** [comment] 2018-09-17 18:07
@apoorvar are you okay with us updating the files in your SimTK project so they are more compatible with 4.0 (and still compatible with 3.3)? Do we need access to your SimTK project?

**Comment by scrum2a** [comment] 2018-09-17 18:08
@jimmyDunne is taking some ownership of this.

**Comment by chrisdembia** [comment] 2018-09-17 21:53
Alternatively, @jimmyDunne if you update the files I can upload them later on.

**Comment by jimmyDunne** [comment] 2018-10-12 16:24
The package has been updated and just needs to be posted to the simTK project.

**Comment by chrisdembia** [comment] 2018-10-12 17:11
Where are the files so that I can post them?

**Comment by jimmyDunne** [comment] 2018-10-12 17:33
In your email.

**Comment by chrisdembia** [comment] 2018-10-12 17:35
Ooops thanks.

**Comment by chrisdembia** [comment] 2018-10-12 23:15
I've updated the releases for the [Rajagopal model SimTK page](https://simtk.org/frs/?group_id=773):

<img width="694" alt="image" src="https://user-images.githubusercontent.com/846001/46897827-f09bcc00-ce39-11e8-906e-bf3e2eb5e734.png">

<img width="681" alt="image" src="https://user-images.githubusercontent.com/846001/46897833-f691ad00-ce39-11e8-98bf-dde0e25ef9b6.png">

Note: I additionally gave names to some PathWrap objects, just as in https://github.com/opensim-org/opensim-models/pull/95.

**Comment by apoorvar** [comment] 2018-10-12 23:31
Thanks Chris and James!

**Closed** 2018-10-19 21:10 UTC
Labels: Needs Discussion
